/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InteriorDesignRouteImport } from './routes/interior-design'
import { Route as InteriorsRouteImport } from './routes/interiors'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminB2bRouteImport } from './routes/admin.b2b'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminInteriorsRouteImport } from './routes/admin.interiors'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as B2bIndexRouteImport } from './routes/b2b.index'
import { Route as B2bEnquiryRouteImport } from './routes/b2b.enquiry'
import { Route as InteriorDesignIndexRouteImport } from './routes/interior-design.index'
import { Route as InteriorDesignConsultationRouteImport } from './routes/interior-design.consultation'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportAboutRouteImport } from './routes/support.about'
import { Route as SupportFaqRouteImport } from './routes/support.faq'
import { Route as SupportPrivacyRouteImport } from './routes/support.privacy'
import { Route as SupportReturnsRouteImport } from './routes/support.returns'
import { Route as SupportShippingRouteImport } from './routes/support.shipping'
import { Route as SupportTermsRouteImport } from './routes/support.terms'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as B2bCatalogueIndexRouteImport } from './routes/b2b.catalogue.index'
import { Route as B2bCatalogueCategoryRouteImport } from './routes/b2b.catalogue.$category'
import { Route as B2bProductProductIdRouteImport } from './routes/b2b.product.$productId'
import { Route as InteriorDesignPortfolioIndexRouteImport } from './routes/interior-design.portfolio.index'
import { Route as InteriorDesignPortfolioProjectIdRouteImport } from './routes/interior-design.portfolio.$projectId'
import { Route as InteriorDesignStylesStyleIdRouteImport } from './routes/interior-design.styles.$styleId'
import { Route as ShopCategorySubcategoryRouteImport } from './routes/shop.$category.$subcategory'
import { Route as ShopProductProductIdRouteImport } from './routes/shop.product.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorDesignRoute = InteriorDesignRouteImport.update({
  id: '/interior-design',
  path: '/interior-design',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorsRoute = InteriorsRouteImport.update({
  id: '/interiors',
  path: '/interiors',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/account/reviews',
  path: '/account/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/account/support',
  path: '/account/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/account/wishlist',
  path: '/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminB2bRoute = AdminB2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInteriorsRoute = AdminInteriorsRouteImport.update({
  id: '/interiors',
  path: '/interiors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const B2bIndexRoute = B2bIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => B2bRoute,
} as any)
const B2bEnquiryRoute = B2bEnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => B2bRoute,
} as any)
const InteriorDesignIndexRoute = InteriorDesignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InteriorDesignRoute,
} as any)
const InteriorDesignConsultationRoute =
  InteriorDesignConsultationRouteImport.update({
    id: '/consultation',
    path: '/consultation',
    getParentRoute: () => InteriorDesignRoute,
  } as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportAboutRoute = SupportAboutRouteImport.update({
  id: '/support/about',
  path: '/support/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportFaqRoute = SupportFaqRouteImport.update({
  id: '/support/faq',
  path: '/support/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportPrivacyRoute = SupportPrivacyRouteImport.update({
  id: '/support/privacy',
  path: '/support/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportReturnsRoute = SupportReturnsRouteImport.update({
  id: '/support/returns',
  path: '/support/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportShippingRoute = SupportShippingRouteImport.update({
  id: '/support/shipping',
  path: '/support/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTermsRoute = SupportTermsRouteImport.update({
  id: '/support/terms',
  path: '/support/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/account/orders/$orderId',
  path: '/account/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const B2bCatalogueIndexRoute = B2bCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => B2bRoute,
} as any)
const B2bCatalogueCategoryRoute = B2bCatalogueCategoryRouteImport.update({
  id: '/catalogue/$category',
  path: '/catalogue/$category',
  getParentRoute: () => B2bRoute,
} as any)
const B2bProductProductIdRoute = B2bProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => B2bRoute,
} as any)
const InteriorDesignPortfolioIndexRoute =
  InteriorDesignPortfolioIndexRouteImport.update({
    id: '/portfolio/',
    path: '/portfolio/',
    getParentRoute: () => InteriorDesignRoute,
  } as any)
const InteriorDesignPortfolioProjectIdRoute =
  InteriorDesignPortfolioProjectIdRouteImport.update({
    id: '/portfolio/$projectId',
    path: '/portfolio/$projectId',
    getParentRoute: () => InteriorDesignRoute,
  } as any)
const InteriorDesignStylesStyleIdRoute =
  InteriorDesignStylesStyleIdRouteImport.update({
    id: '/styles/$styleId',
    path: '/styles/$styleId',
    getParentRoute: () => InteriorDesignRoute,
  } as any)
const ShopCategorySubcategoryRoute = ShopCategorySubcategoryRouteImport.update({
  id: '/$subcategory',
  path: '/$subcategory',
  getParentRoute: () => ShopCategoryRoute,
} as any)
const ShopProductProductIdRoute = ShopProductProductIdRouteImport.update({
  id: '/shop/product/$productId',
  path: '/shop/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/b2b': typeof B2bRouteWithChildren
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/compare': typeof CompareRoute
  '/home': typeof HomeRoute
  '/interior-design': typeof InteriorDesignRouteWithChildren
  '/interiors': typeof InteriorsRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/b2b': typeof AdminB2bRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/interiors': typeof AdminInteriorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/b2b/enquiry': typeof B2bEnquiryRoute
  '/interior-design/consultation': typeof InteriorDesignConsultationRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/shop/$category': typeof ShopCategoryRouteWithChildren
  '/support/about': typeof SupportAboutRoute
  '/support/faq': typeof SupportFaqRoute
  '/support/privacy': typeof SupportPrivacyRoute
  '/support/returns': typeof SupportReturnsRoute
  '/support/shipping': typeof SupportShippingRoute
  '/support/terms': typeof SupportTermsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/b2b/': typeof B2bIndexRoute
  '/interior-design/': typeof InteriorDesignIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/support/': typeof SupportIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/b2b/catalogue/$category': typeof B2bCatalogueCategoryRoute
  '/b2b/product/$productId': typeof B2bProductProductIdRoute
  '/interior-design/portfolio/$projectId': typeof InteriorDesignPortfolioProjectIdRoute
  '/interior-design/styles/$styleId': typeof InteriorDesignStylesStyleIdRoute
  '/shop/$category/$subcategory': typeof ShopCategorySubcategoryRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/b2b/catalogue/': typeof B2bCatalogueIndexRoute
  '/interior-design/portfolio/': typeof InteriorDesignPortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/compare': typeof CompareRoute
  '/home': typeof HomeRoute
  '/interiors': typeof InteriorsRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/b2b': typeof AdminB2bRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/interiors': typeof AdminInteriorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/b2b/enquiry': typeof B2bEnquiryRoute
  '/interior-design/consultation': typeof InteriorDesignConsultationRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/shop/$category': typeof ShopCategoryRouteWithChildren
  '/support/about': typeof SupportAboutRoute
  '/support/faq': typeof SupportFaqRoute
  '/support/privacy': typeof SupportPrivacyRoute
  '/support/returns': typeof SupportReturnsRoute
  '/support/shipping': typeof SupportShippingRoute
  '/support/terms': typeof SupportTermsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/b2b': typeof B2bIndexRoute
  '/interior-design': typeof InteriorDesignIndexRoute
  '/shop': typeof ShopIndexRoute
  '/support': typeof SupportIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/b2b/catalogue/$category': typeof B2bCatalogueCategoryRoute
  '/b2b/product/$productId': typeof B2bProductProductIdRoute
  '/interior-design/portfolio/$projectId': typeof InteriorDesignPortfolioProjectIdRoute
  '/interior-design/styles/$styleId': typeof InteriorDesignStylesStyleIdRoute
  '/shop/$category/$subcategory': typeof ShopCategorySubcategoryRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/b2b/catalogue': typeof B2bCatalogueIndexRoute
  '/interior-design/portfolio': typeof InteriorDesignPortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/b2b': typeof B2bRouteWithChildren
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/compare': typeof CompareRoute
  '/home': typeof HomeRoute
  '/interior-design': typeof InteriorDesignRouteWithChildren
  '/interiors': typeof InteriorsRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/b2b': typeof AdminB2bRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/interiors': typeof AdminInteriorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/b2b/enquiry': typeof B2bEnquiryRoute
  '/interior-design/consultation': typeof InteriorDesignConsultationRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/shop/$category': typeof ShopCategoryRouteWithChildren
  '/support/about': typeof SupportAboutRoute
  '/support/faq': typeof SupportFaqRoute
  '/support/privacy': typeof SupportPrivacyRoute
  '/support/returns': typeof SupportReturnsRoute
  '/support/shipping': typeof SupportShippingRoute
  '/support/terms': typeof SupportTermsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/b2b/': typeof B2bIndexRoute
  '/interior-design/': typeof InteriorDesignIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/support/': typeof SupportIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/b2b/catalogue/$category': typeof B2bCatalogueCategoryRoute
  '/b2b/product/$productId': typeof B2bProductProductIdRoute
  '/interior-design/portfolio/$projectId': typeof InteriorDesignPortfolioProjectIdRoute
  '/interior-design/styles/$styleId': typeof InteriorDesignStylesStyleIdRoute
  '/shop/$category/$subcategory': typeof ShopCategorySubcategoryRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/b2b/catalogue/': typeof B2bCatalogueIndexRoute
  '/interior-design/portfolio/': typeof InteriorDesignPortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/b2b'
    | '/brands'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/compare'
    | '/home'
    | '/interior-design'
    | '/interiors'
    | '/wishlist'
    | '/account/addresses'
    | '/account/login'
    | '/account/profile'
    | '/account/reviews'
    | '/account/support'
    | '/account/wishlist'
    | '/admin/b2b'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/interiors'
    | '/admin/login'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/users'
    | '/b2b/enquiry'
    | '/interior-design/consultation'
    | '/order/$orderId'
    | '/shop/$category'
    | '/support/about'
    | '/support/faq'
    | '/support/privacy'
    | '/support/returns'
    | '/support/shipping'
    | '/support/terms'
    | '/account/'
    | '/admin/'
    | '/b2b/'
    | '/interior-design/'
    | '/shop/'
    | '/support/'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/b2b/catalogue/$category'
    | '/b2b/product/$productId'
    | '/interior-design/portfolio/$projectId'
    | '/interior-design/styles/$styleId'
    | '/shop/$category/$subcategory'
    | '/shop/product/$productId'
    | '/admin/orders/'
    | '/b2b/catalogue/'
    | '/interior-design/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/compare'
    | '/home'
    | '/interiors'
    | '/wishlist'
    | '/account/addresses'
    | '/account/login'
    | '/account/profile'
    | '/account/reviews'
    | '/account/support'
    | '/account/wishlist'
    | '/admin/b2b'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/interiors'
    | '/admin/login'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/users'
    | '/b2b/enquiry'
    | '/interior-design/consultation'
    | '/order/$orderId'
    | '/shop/$category'
    | '/support/about'
    | '/support/faq'
    | '/support/privacy'
    | '/support/returns'
    | '/support/shipping'
    | '/support/terms'
    | '/account'
    | '/admin'
    | '/b2b'
    | '/interior-design'
    | '/shop'
    | '/support'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/b2b/catalogue/$category'
    | '/b2b/product/$productId'
    | '/interior-design/portfolio/$projectId'
    | '/interior-design/styles/$styleId'
    | '/shop/$category/$subcategory'
    | '/shop/product/$productId'
    | '/admin/orders'
    | '/b2b/catalogue'
    | '/interior-design/portfolio'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/b2b'
    | '/brands'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/compare'
    | '/home'
    | '/interior-design'
    | '/interiors'
    | '/wishlist'
    | '/account/addresses'
    | '/account/login'
    | '/account/profile'
    | '/account/reviews'
    | '/account/support'
    | '/account/wishlist'
    | '/admin/b2b'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/interiors'
    | '/admin/login'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/users'
    | '/b2b/enquiry'
    | '/interior-design/consultation'
    | '/order/$orderId'
    | '/shop/$category'
    | '/support/about'
    | '/support/faq'
    | '/support/privacy'
    | '/support/returns'
    | '/support/shipping'
    | '/support/terms'
    | '/account/'
    | '/admin/'
    | '/b2b/'
    | '/interior-design/'
    | '/shop/'
    | '/support/'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/b2b/catalogue/$category'
    | '/b2b/product/$productId'
    | '/interior-design/portfolio/$projectId'
    | '/interior-design/styles/$styleId'
    | '/shop/$category/$subcategory'
    | '/shop/product/$productId'
    | '/admin/orders/'
    | '/b2b/catalogue/'
    | '/interior-design/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  B2bRoute: typeof B2bRouteWithChildren
  BrandsRoute: typeof BrandsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRoute
  CompareRoute: typeof CompareRoute
  HomeRoute: typeof HomeRoute
  InteriorDesignRoute: typeof InteriorDesignRouteWithChildren
  InteriorsRoute: typeof InteriorsRoute
  WishlistRoute: typeof WishlistRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ShopCategoryRoute: typeof ShopCategoryRouteWithChildren
  SupportAboutRoute: typeof SupportAboutRoute
  SupportFaqRoute: typeof SupportFaqRoute
  SupportPrivacyRoute: typeof SupportPrivacyRoute
  SupportReturnsRoute: typeof SupportReturnsRoute
  SupportShippingRoute: typeof SupportShippingRoute
  SupportTermsRoute: typeof SupportTermsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  ShopProductProductIdRoute: typeof ShopProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-design': {
      id: '/interior-design'
      path: '/interior-design'
      fullPath: '/interior-design'
      preLoaderRoute: typeof InteriorDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interiors': {
      id: '/interiors'
      path: '/interiors'
      fullPath: '/interiors'
      preLoaderRoute: typeof InteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/account/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/support': {
      id: '/account/support'
      path: '/account/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/account/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/b2b': {
      id: '/admin/b2b'
      path: '/b2b'
      fullPath: '/admin/b2b'
      preLoaderRoute: typeof AdminB2bRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interiors': {
      id: '/admin/interiors'
      path: '/interiors'
      fullPath: '/admin/interiors'
      preLoaderRoute: typeof AdminInteriorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/b2b/': {
      id: '/b2b/'
      path: '/'
      fullPath: '/b2b/'
      preLoaderRoute: typeof B2bIndexRouteImport
      parentRoute: typeof B2bRoute
    }
    '/b2b/enquiry': {
      id: '/b2b/enquiry'
      path: '/enquiry'
      fullPath: '/b2b/enquiry'
      preLoaderRoute: typeof B2bEnquiryRouteImport
      parentRoute: typeof B2bRoute
    }
    '/interior-design/': {
      id: '/interior-design/'
      path: '/'
      fullPath: '/interior-design/'
      preLoaderRoute: typeof InteriorDesignIndexRouteImport
      parentRoute: typeof InteriorDesignRoute
    }
    '/interior-design/consultation': {
      id: '/interior-design/consultation'
      path: '/consultation'
      fullPath: '/interior-design/consultation'
      preLoaderRoute: typeof InteriorDesignConsultationRouteImport
      parentRoute: typeof InteriorDesignRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/about': {
      id: '/support/about'
      path: '/support/about'
      fullPath: '/support/about'
      preLoaderRoute: typeof SupportAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/faq': {
      id: '/support/faq'
      path: '/support/faq'
      fullPath: '/support/faq'
      preLoaderRoute: typeof SupportFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/privacy': {
      id: '/support/privacy'
      path: '/support/privacy'
      fullPath: '/support/privacy'
      preLoaderRoute: typeof SupportPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/returns': {
      id: '/support/returns'
      path: '/support/returns'
      fullPath: '/support/returns'
      preLoaderRoute: typeof SupportReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/shipping': {
      id: '/support/shipping'
      path: '/support/shipping'
      fullPath: '/support/shipping'
      preLoaderRoute: typeof SupportShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/terms': {
      id: '/support/terms'
      path: '/support/terms'
      fullPath: '/support/terms'
      preLoaderRoute: typeof SupportTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/account/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/b2b/catalogue/': {
      id: '/b2b/catalogue/'
      path: '/catalogue'
      fullPath: '/b2b/catalogue/'
      preLoaderRoute: typeof B2bCatalogueIndexRouteImport
      parentRoute: typeof B2bRoute
    }
    '/b2b/catalogue/$category': {
      id: '/b2b/catalogue/$category'
      path: '/catalogue/$category'
      fullPath: '/b2b/catalogue/$category'
      preLoaderRoute: typeof B2bCatalogueCategoryRouteImport
      parentRoute: typeof B2bRoute
    }
    '/b2b/product/$productId': {
      id: '/b2b/product/$productId'
      path: '/product/$productId'
      fullPath: '/b2b/product/$productId'
      preLoaderRoute: typeof B2bProductProductIdRouteImport
      parentRoute: typeof B2bRoute
    }
    '/interior-design/portfolio/': {
      id: '/interior-design/portfolio/'
      path: '/portfolio'
      fullPath: '/interior-design/portfolio/'
      preLoaderRoute: typeof InteriorDesignPortfolioIndexRouteImport
      parentRoute: typeof InteriorDesignRoute
    }
    '/interior-design/portfolio/$projectId': {
      id: '/interior-design/portfolio/$projectId'
      path: '/portfolio/$projectId'
      fullPath: '/interior-design/portfolio/$projectId'
      preLoaderRoute: typeof InteriorDesignPortfolioProjectIdRouteImport
      parentRoute: typeof InteriorDesignRoute
    }
    '/interior-design/styles/$styleId': {
      id: '/interior-design/styles/$styleId'
      path: '/styles/$styleId'
      fullPath: '/interior-design/styles/$styleId'
      preLoaderRoute: typeof InteriorDesignStylesStyleIdRouteImport
      parentRoute: typeof InteriorDesignRoute
    }
    '/shop/$category/$subcategory': {
      id: '/shop/$category/$subcategory'
      path: '/$subcategory'
      fullPath: '/shop/$category/$subcategory'
      preLoaderRoute: typeof ShopCategorySubcategoryRouteImport
      parentRoute: typeof ShopCategoryRoute
    }
    '/shop/product/$productId': {
      id: '/shop/product/$productId'
      path: '/shop/product/$productId'
      fullPath: '/shop/product/$productId'
      preLoaderRoute: typeof ShopProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminB2bRoute: typeof AdminB2bRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminInteriorsRoute: typeof AdminInteriorsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminB2bRoute: AdminB2bRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminInteriorsRoute: AdminInteriorsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface B2bRouteChildren {
  B2bEnquiryRoute: typeof B2bEnquiryRoute
  B2bIndexRoute: typeof B2bIndexRoute
  B2bCatalogueCategoryRoute: typeof B2bCatalogueCategoryRoute
  B2bProductProductIdRoute: typeof B2bProductProductIdRoute
  B2bCatalogueIndexRoute: typeof B2bCatalogueIndexRoute
}

const B2bRouteChildren: B2bRouteChildren = {
  B2bEnquiryRoute: B2bEnquiryRoute,
  B2bIndexRoute: B2bIndexRoute,
  B2bCatalogueCategoryRoute: B2bCatalogueCategoryRoute,
  B2bProductProductIdRoute: B2bProductProductIdRoute,
  B2bCatalogueIndexRoute: B2bCatalogueIndexRoute,
}

const B2bRouteWithChildren = B2bRoute._addFileChildren(B2bRouteChildren)

interface InteriorDesignRouteChildren {
  InteriorDesignConsultationRoute: typeof InteriorDesignConsultationRoute
  InteriorDesignIndexRoute: typeof InteriorDesignIndexRoute
  InteriorDesignPortfolioProjectIdRoute: typeof InteriorDesignPortfolioProjectIdRoute
  InteriorDesignStylesStyleIdRoute: typeof InteriorDesignStylesStyleIdRoute
  InteriorDesignPortfolioIndexRoute: typeof InteriorDesignPortfolioIndexRoute
}

const InteriorDesignRouteChildren: InteriorDesignRouteChildren = {
  InteriorDesignConsultationRoute: InteriorDesignConsultationRoute,
  InteriorDesignIndexRoute: InteriorDesignIndexRoute,
  InteriorDesignPortfolioProjectIdRoute: InteriorDesignPortfolioProjectIdRoute,
  InteriorDesignStylesStyleIdRoute: InteriorDesignStylesStyleIdRoute,
  InteriorDesignPortfolioIndexRoute: InteriorDesignPortfolioIndexRoute,
}

const InteriorDesignRouteWithChildren = InteriorDesignRoute._addFileChildren(
  InteriorDesignRouteChildren,
)

interface ShopCategoryRouteChildren {
  ShopCategorySubcategoryRoute: typeof ShopCategorySubcategoryRoute
}

const ShopCategoryRouteChildren: ShopCategoryRouteChildren = {
  ShopCategorySubcategoryRoute: ShopCategorySubcategoryRoute,
}

const ShopCategoryRouteWithChildren = ShopCategoryRoute._addFileChildren(
  ShopCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  B2bRoute: B2bRouteWithChildren,
  BrandsRoute: BrandsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRoute,
  CompareRoute: CompareRoute,
  HomeRoute: HomeRoute,
  InteriorDesignRoute: InteriorDesignRouteWithChildren,
  InteriorsRoute: InteriorsRoute,
  WishlistRoute: WishlistRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountSupportRoute: AccountSupportRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ShopCategoryRoute: ShopCategoryRouteWithChildren,
  SupportAboutRoute: SupportAboutRoute,
  SupportFaqRoute: SupportFaqRoute,
  SupportPrivacyRoute: SupportPrivacyRoute,
  SupportReturnsRoute: SupportReturnsRoute,
  SupportShippingRoute: SupportShippingRoute,
  SupportTermsRoute: SupportTermsRoute,
  AccountIndexRoute: AccountIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  ShopProductProductIdRoute: ShopProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
